"""Python mobile automation toolkit."""

from .adb import (
    AdbClient,
    AdbError,
    Device,
    DeviceOfflineError,
    DeviceReconnectError,
    DeviceUnavailableError,
)
from .feishu import (
    DEFAULT_CONFIG_PATH,
    FeishuConfig,
    FeishuError,
    load_feishu_config,
    send_feishu_text,
)
from .runner import TaskRunner
from .outreach import (
    UserFilter,
    build_outreach_plan,
    load_contacted_user_ids,
    write_outreach_plan,
)
from .messaging import (
    MessageResult,
    MessageListItem,
    MessageTarget,
    MessagingTimeout,
    PoppoMessenger,
    UserNotFound,
    UserOffline,
    append_message_history,
    chat_messages,
    find_exact_user_card,
    find_live_home_search_button,
    is_online_profile_status,
    latest_history_by_user,
    load_approved_targets,
    load_message_templates,
    message_list_items,
    new_incoming_reply,
    nicknames_match,
    profile_online_status,
    reply_after_outgoing,
)
from .square import PageState, RunState, collect_square_users, open_square_page
from .ui import Bounds, UiNode, UiTree

__all__ = [
    "AdbClient",
    "AdbError",
    "Bounds",
    "collect_square_users",
    "Device",
    "DeviceOfflineError",
    "DeviceReconnectError",
    "DeviceUnavailableError",
    "DEFAULT_CONFIG_PATH",
    "FeishuConfig",
    "FeishuError",
    "load_feishu_config",
    "open_square_page",
    "PageState",
    "RunState",
    "send_feishu_text",
    "TaskRunner",
    "UiNode",
    "UiTree",
    "UserFilter",
    "build_outreach_plan",
    "load_contacted_user_ids",
    "write_outreach_plan",
    "MessageResult",
    "MessageListItem",
    "MessageTarget",
    "MessagingTimeout",
    "PoppoMessenger",
    "UserNotFound",
    "UserOffline",
    "append_message_history",
    "chat_messages",
    "find_exact_user_card",
    "find_live_home_search_button",
    "is_online_profile_status",
    "latest_history_by_user",
    "load_approved_targets",
    "load_message_templates",
    "message_list_items",
    "new_incoming_reply",
    "nicknames_match",
    "profile_online_status",
    "reply_after_outgoing",
]
__version__ = "0.1.0"
